// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://exluhngzdhrmsjfheucn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV4bHVobmd6ZGhybXNqZmhldWNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkzMjg5NDIsImV4cCI6MjA4NDkwNDk0Mn0.7TNHtLhR0JHy7eld4muJfbvLJZkDBflaMSmni6KPuGA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});